#pragma kernel CSMain

struct ParticleData
{
    float3 position;
    float3 velocity;
    float4 color;
};

StructuredBuffer<ParticleData> _particlesDataRead;
RWStructuredBuffer<ParticleData> _particlesDataWrite;
int size;

float deltaTime;
float time;

// Spatial Hashing
StructuredBuffer<uint2> _sortBuffer;
StructuredBuffer<uint2> _cellOffsetsBuffer;
float _Radius;
uint _TableSize;

// Render Texture
Texture2D<float4> _LandscapeTexture;
SamplerState sampler_LandscapeTexture;

// Mouse
float2 _mousePosition;
int _isMouseClicked;

// Simulation parameters
float _repulsionStrength = 10.0;
float _cohesionStrength = 0.1;

int2 GetCell(float3 pos)
{
    return int2(floor(pos.x / _Radius), floor(pos.z / _Radius));
}

uint HashCell(int2 cell)
{
    const uint p1 = 73856093;
    const uint p2 = 19349663;
    uint h = (uint(cell.x) * p1) ^ (uint(cell.y) * p2);
    return h % _TableSize;
}

[numthreads(4,1,4)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int index = id.x * size + id.z;
    ParticleData particleData;

    if (index >= size * size) return;

    particleData = _particlesDataRead[index];


    // --- Ajust velocity ---
    // Mouse impact
    if (_isMouseClicked == 1)
    {
        float3 mousePos = float3(_mousePosition.x, 0, _mousePosition.y);
        float3 direction = mousePos - particleData.position;
        float distance = length(direction);

        if (distance > 0.0001 && distance < 1.0)
        {
            float force = (1.0 - distance) * 100.0;
            particleData.velocity += normalize(direction) * -force * deltaTime;
        }
    }

    // Repulsion & cohesion impact
    int neighborCount = 0;
    int2 myCell = GetCell(particleData.position);
    for (int ox = -1; ox <= 1; ox++)
    {
        for (int oz = -1; oz <= 1; oz++)
        {
            uint hash = HashCell(myCell + int2(ox, oz));
            uint2 bounds = _cellOffsetsBuffer[hash];

            for (uint j = bounds.x; j < bounds.y; j++)
            {
                uint otherIndex = _sortBuffer[j].y;
                if (otherIndex == (uint)index) continue;
                ParticleData otherParticle = _particlesDataRead[otherIndex];
                float3 direction = particleData.position - otherParticle.position;
                float distance = length(direction.xz);
                neighborCount++;

                if (distance < _Radius / 2.0) // Repulsion
                {
                    float force = (_Radius / 2.0 - distance) * _repulsionStrength;
                    particleData.velocity += normalize(direction) * force * deltaTime;
                }
                else if (distance < _Radius) // Cohesion
                {
                    float force = (_Radius - distance) * _cohesionStrength;
                    particleData.velocity -= normalize(direction) * force * deltaTime;
                }
            }
        }
    }

    // Keep the simulation on the xOz plane.
    particleData.velocity.y = 0.0;
    particleData.velocity *= 0.95;

    // gravity
    // particleData.velocity.x += 9.81 * deltaTime;

    // --- Ajust position ---
    float wallLimit = 6.0;
    particleData.position += particleData.velocity * deltaTime;
    particleData.position.y = 0.0;

    float wallRestitution = 0.7;

    if (particleData.position.x < -wallLimit)
    {
        particleData.position.x = -wallLimit;
        particleData.velocity.x = abs(particleData.velocity.x) * wallRestitution;
    }
    else if (particleData.position.x > wallLimit)
    {
        particleData.position.x = wallLimit;
        particleData.velocity.x = -abs(particleData.velocity.x) * wallRestitution;
    }

    if (particleData.position.z < -wallLimit)
    {
        particleData.position.z = -wallLimit;
        particleData.velocity.z = abs(particleData.velocity.z) * wallRestitution;
    }
    else if (particleData.position.z > wallLimit)
    {
        particleData.position.z = wallLimit;
        particleData.velocity.z = -abs(particleData.velocity.z) * wallRestitution;
    }

    // --- Ajust color ---
    float textureHorizontalScale = 2560.0 / 1440.0;

    // Rotate world pos 90 degrees around Y axis
    float3 rotatedPos = float3(particleData.position.z, particleData.position.y, -particleData.position.x);

    rotatedPos.x /= textureHorizontalScale;

    float2 uv = saturate((rotatedPos.xz) / 1.85 / 10.0 + 0.5);
    float4 colorFromTexture = _LandscapeTexture.SampleLevel(sampler_LandscapeTexture, uv, 0.0);
    particleData.color = colorFromTexture * 2.0;

    // --- Update particle data ---
    _particlesDataWrite[index] = particleData;
}
